### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by adriannowaq** [vov4uk/Hik.Api#2]
Hi, I'm using code from your README and keep getting this exception

```
Hik.Api.HikException
  HResult=0x80131500
  Message=() => NET_DVR_FindPicture(value(Hik.Api.Services.HikPhotoService+<>c__DisplayClass3_0).userId, value(Hik.Api.Services.HikPhotoService+<>c__DisplayClass3_0).findConditions)
  Source=Hik.Api
  StackTrace:
   at Hik.Api.Helpers.SdkHelper.InvokeSDK[T](Expression`1 func)
   at Hik.Api.Services.HikPhotoService.StartFind(Int32 userId, DateTime periodStart, DateTime periodEnd, Int32 channel)
   at Hik.Api.Services.FileService.<FindFilesAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Hik.Test.Program.<Main>d__0.MoveNext() in C:\Users\User\source\repos\Hik.Test\Hik.Test\Program.cs:line 21
```

SDk Logs
```
[2022-03-11 13:48:57.777][INF] The COM:Core ver is 5.3.6.30, 2018_08_16. Async:1.
[2022-03-11 13:48:57.777][DBG] CCoreGlobalCtrl::GetHCNetUtilsAPI, new HCNetUtilsAPI SUCC
[2022-03-11 13:48:57.777][DBG] CCoreGlobalCtrl::GetHCNetUtilsAPI, Init, SUCC, m_pHCNetUtilsAPI[1691888912]
[2022-03-11 13:48:57.777][DBG] CCoreGlobalCtrl::GetHCNetUtilsAPI, m_pHCNetUtilsAPI[1691888912]
[2022-03-11 13:48:57.777][INF] This hcnetsdk ver is 5.3.6.30 Ver 2018_08_16.
[2022-03-11 13:48:57.781][INF] login dev 192.168.4.212:23681.
[2022-03-11 13:48:57.799][INF] Private connect 192.168.4.212:23681 sock=1132 this=0x672bdd44 cmd=0x10000 port=51364
[2022-03-11 13:48:57.799][INF] LogonDev1 in[192.168.4.212:23681]
[2022-03-11 13:48:58.111][DBG] load[C:\Users\User\source\repos\Hik.Test\Hik.Test\bin\Debug\net5.0\SDK\HCNetSDKCom/HCPlayBack.dll] succ
[2022-03-11 13:48:58.111][INF] AbilityAnalyze---Init-- start
[2022-03-11 13:48:58.133][INF] The COM:HCPlayback ver is 5.3.6.30, 2018_08_16.
[2022-03-11 13:48:58.143][INF] Private connect 192.168.4.212:23681 sock=1192 this=0x672be328 cmd=0x111148 port=51366
[2022-03-11 13:48:58.194][ERR] Index[0] cmd[111148] SendCommandWithRecv failed 
```

**Comment by vov4uk** [comment]
@adriannowaq I'll take a look on the weekend. Could you please provide Program.cs? 
Do not forget to remove the password.

**Comment by vov4uk** [comment]
Hi @adriannowaq, added console app [sample](https://raw.githubusercontent.com/vov4uk/Hik.Api/main/sample/Program.cs), with logs. Try it.  If you still have errors, please let me know.

**Comment by adriannowaq** [comment]
```
App started
Login success
() => NET_DVR_FindPicture(value(Hik.Api.Services.HikPhotoService+<>c__DisplayClass3_0).userId, value(Hik.Api.Services.HikPhotoService+<>c__DisplayClass3_0).findConditions)
Device does not support this function.
   at Hik.Api.Helpers.SdkHelper.InvokeSDK[T](Expression`1 func)
   at Hik.Api.Services.HikPhotoService.StartFind(Int32 userId, DateTime periodStart, DateTime periodEnd, Int32 channel)
   at Hik.Api.Services.FileService.FindFilesAsync(DateTime periodStart, DateTime periodEnd, Session session)
   at ConsoleApp.Program.Main(String[] args) in C:\Users\User\source\repos\Hik.Test\Hik.Test\Program.cs:line 29
```

**Comment by adriannowaq** [comment]
When I delete FindPhotos()

I'm getting:

```
App started
Login success
() => NET_DVR_FindFile_V40(value(Hik.Api.Services.HikVideoService+<>c__DisplayClass5_0).userId, value(Hik.Api.Services.HikVideoService+<>c__DisplayClass5_0).findConditions)
Channel number error. There is no corresponding channel number on the device.
   at Hik.Api.Helpers.SdkHelper.InvokeSDK[T](Expression`1 func)
   at Hik.Api.Services.HikVideoService.StartFind(Int32 userId, DateTime periodStart, DateTime periodEnd, Int32 channel)
   at Hik.Api.Services.FileService.FindFilesAsync(DateTime periodStart, DateTime periodEnd, Session session)
   at ConsoleApp.Program.Main(String[] args) in C:\Users\User\source\repos\Hik.Test\Hik.Test\Program.cs:line 40

```

**Comment by vov4uk** [comment]
OK, look like camera configuration issue. Let's try next.
* Download Hikvision C# SDK https://www.hikvision.com/en/support/download/sdk/device-network-sdk--for-windows-64-bit-/
* Unzip it and run \C# demo\7-Remote configuration.zip\
* I'm interested in channel settings
![image](https://user-images.githubusercontent.com/2099449/158025202-4ee7d2f4-201e-49ef-81bd-a9f74c4a9d76.png)
* Also you can try 2-Preview-NVRCsharpDemo.zip to preview stream from camera. Try if your camera works with SDK correctly

**Comment by adriannowaq** [comment]
![image](https://user-images.githubusercontent.com/57181007/158121234-9cd0d041-a087-47a3-979c-0bf924e04475.png)

Also it works for me when I use Preview-NVRCSharpDemo

**Comment by vov4uk** [comment]
Hi @adriannowaq 
Please take a look at a branch [Connection_problem](https://github.com/vov4uk/Hik.Api/tree/Connection_problem), 
Run ConsoleApp. I've committed a possible fix.

**Comment by adriannowaq** [comment]
```
App started
Login success
() => NET_DVR_FindPicture(value(Hik.Api.Services.HikPhotoService+<>c__DisplayClass3_0).userId, value(Hik.Api.Services.HikPhotoService+<>c__DisplayClass3_0).findConditions)
Device does not support this function.
   at Hik.Api.Helpers.SdkHelper.InvokeSDK[T](Expression`1 func) in C:\Users\User\Downloads\Hik.Api-Connection_problem\Hik.Api-Connection_problem\src\Hik.Api\Helpers\SDKHelper.cs:line 18
   at Hik.Api.Services.HikPhotoService.StartFind(Int32 userId, DateTime periodStart, DateTime periodEnd, Int32 channel) in C:\Users\User\Downloads\Hik.Api-Connection_problem\Hik.Api-Connection_problem\src\Hik.Api\Services\HikPhotoService.cs:line 59
   at Hik.Api.Services.FileService.FindFilesAsync(DateTime periodStart, DateTime periodEnd, Session session) in C:\Users\User\Downloads\Hik.Api-Connection_problem\Hik.Api-Connection_problem\src\Hik.Api\Services\FileService.cs:line 14
   at ConsoleApp.Program.Main(String[] args) in C:\Users\User\Downloads\Hik.Api-Connection_problem\Hik.Api-Connection_problem\sample\Program.cs:line 29
```

**Comment by vov4uk** [comment]
@adriannowaq Ok, try delete FindPhotos()

**Comment by adriannowaq** [comment]
```
App started
Login success
() => NET_DVR_FindFile_V40(value(Hik.Api.Services.HikVideoService+<>c__DisplayClass5_0).userId, value(Hik.Api.Services.HikVideoService+<>c__DisplayClass5_0).findConditions)
Channel number error. There is no corresponding channel number on the device.
   at Hik.Api.Helpers.SdkHelper.InvokeSDK[T](Expression`1 func) in C:\Users\User\Downloads\Hik.Api-Connection_problem\Hik.Api-Connection_problem\src\Hik.Api\Helpers\SDKHelper.cs:line 18
   at Hik.Api.Services.HikVideoService.StartFind(Int32 userId, DateTime periodStart, DateTime periodEnd, Int32 channel) in C:\Users\User\Downloads\Hik.Api-Connection_problem\Hik.Api-Connection_problem\src\Hik.Api\Services\HikVideoService.cs:line 55
   at Hik.Api.Services.FileService.FindFilesAsync(DateTime periodStart, DateTime periodEnd, Session session) in C:\Users\User\Downloads\Hik.Api-Connection_problem\Hik.Api-Connection_problem\src\Hik.Api\Services\FileService.cs:line 14
   at ConsoleApp.Program.Main(String[] args) in C:\Users\User\Downloads\Hik.Api-Connection_problem\Hik.Api-Connection_problem\sample\Program.cs:line 39
```

**Comment by vov4uk** [comment]
Last idea - try \C# demo\3-playback&doanload.zip from Hikvision C# SDK
What is your camera model?

**Comment by adriannowaq** [comment]
![image](https://user-images.githubusercontent.com/57181007/158190842-a0eaeaa6-8099-4895-864e-667496322d99.png)
it works

**Comment by adriannowaq** [comment]
It's not camera - it's recorder

**Comment by vov4uk** [comment]
Are you able to download files?

**Comment by vov4uk** [comment]
add me to skype - mr.vov4uk
for faster communication
